# Generated by Django 2.2.5 on 2022-05-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_auto_20220527_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitors',
            old_name='status',
            new_name='is_active',
        ),
    ]
