# Generated by Django 2.2.5 on 2022-05-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_auto_20220528_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='mbl_no',
            field=models.CharField(max_length=50),
        ),
    ]
