# Generated by Django 2.2.5 on 2022-05-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Post', models.CharField(max_length=50)),
                ('Status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
                ('WorkstartTime', models.DateTimeField()),
                ('WorkendTime', models.DateTimeField()),
            ],
        ),
    ]
