# Generated by Django 2.2.5 on 2022-05-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='WorkendTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='officer',
            name='WorkstartTime',
            field=models.TimeField(),
        ),
    ]
