# Generated by Django 2.2.5 on 2022-05-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0004_auto_20220527_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officer',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='officer',
            old_name='Post',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='officer',
            old_name='WorkendTime',
            new_name='workendTime',
        ),
        migrations.RenameField(
            model_name='officer',
            old_name='WorkstartTime',
            new_name='workstartTime',
        ),
        migrations.RenameField(
            model_name='workdays',
            old_name='OfficerID',
            new_name='officerid',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='Status',
        ),
        migrations.AddField(
            model_name='officer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
