# Generated by Django 2.2.5 on 2022-05-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0005_auto_20220527_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workdays',
            old_name='officerid',
            new_name='officer',
        ),
    ]
