# Generated by Django 2.2.5 on 2022-05-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0006_auto_20220530_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdays',
            name='workdays',
            field=models.DurationField(),
        ),
    ]
