# Generated by Django 2.2.5 on 2022-05-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0007_auto_20220530_1701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='workdays',
        ),
    ]
