# Generated by Django 2.2.5 on 2022-05-30 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0008_delete_workdays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workdays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workday_from', models.CharField(choices=[(1, 'Sundays'), (2, 'Mondays'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')], default=1, max_length=50)),
                ('workday_to', models.CharField(choices=[(1, 'Sundays'), (2, 'Mondays'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')], default=1, max_length=50)),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='officer.Officer')),
            ],
        ),
    ]
