# Generated by Django 2.2.5 on 2022-05-31 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0009_workdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdays',
            name='officer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='officer.Officer'),
        ),
        migrations.AlterField(
            model_name='workdays',
            name='workday_from',
            field=models.DecimalField(choices=[('Sunday', 'Sunday'), ('Mondays', 'Mondays'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], decimal_places=0, default=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='workdays',
            name='workday_to',
            field=models.DecimalField(choices=[('Sunday', 'Sunday'), ('Mondays', 'Mondays'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], decimal_places=0, default=4, max_digits=10),
        ),
    ]
