# Generated by Django 2.2.5 on 2022-05-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0009_workdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdays',
            name='workday_from',
            field=models.CharField(choices=[(1, 'Sunday'), (2, 'Mondays'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')], default='Sunday', max_length=50),
        ),
        migrations.AlterField(
            model_name='workdays',
            name='workday_to',
            field=models.CharField(choices=[(1, 'Sunday'), (2, 'Mondays'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')], default='Monday', max_length=50),
        ),
    ]
