# Generated by Django 2.2.5 on 2022-05-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0011_auto_20220530_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdays',
            name='workday_from',
            field=models.DecimalField(choices=[(1, 'Sunday'), (2, 'Mondays'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')], decimal_places=0, default=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='workdays',
            name='workday_to',
            field=models.DecimalField(choices=[(1, 'Sunday'), (2, 'Mondays'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')], decimal_places=0, default=4, max_digits=10),
        ),
    ]
