# Generated by Django 2.2.5 on 2022-06-01 02:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0012_auto_20220531_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdays',
            name='workdays',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sunday', 'Sunday'), ('Mondays', 'Mondays'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Sunday', max_length=100),
        ),
    ]
