# Generated by Django 2.2.5 on 2022-05-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officerID', models.CharField(max_length=100)),
                ('visitorID', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=50)),
                ('Type', models.CharField(choices=[('Leave', 'Leave'), ('appointmnet', 'appointmnet'), ('break', 'break')], default='appointmnet', max_length=50)),
                ('Status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('addedd_on', models.DateTimeField()),
            ],
        ),
    ]
