# Generated by Django 2.2.5 on 2022-05-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_record', '0004_auto_20220527_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='Type',
            new_name='activitytype',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='officerID',
            new_name='officerid',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='visitorID',
            new_name='visitorid',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='Status',
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
