# Generated by Django 2.2.5 on 2022-05-28 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_record', '0005_auto_20220527_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='status',
            new_name='is_active',
        ),
    ]
