# Generated by Django 2.2.5 on 2022-05-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_record', '0006_auto_20220528_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
