# Generated by Django 2.2.5 on 2022-05-28 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_record', '0007_activity_is_cancelled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='name',
            new_name='Comment',
        ),
    ]
