# Generated by Django 2.2.5 on 2022-05-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_record', '0011_auto_20220528_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='addedd_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
