# Generated by Django 2.2.5 on 2022-05-28 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activity_record', '0014_auto_20220528_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='officerid',
            new_name='officer',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='visitorid',
            new_name='visitor',
        ),
        migrations.AlterField(
            model_name='activity',
            name='addedd_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 14, 19, 0, 177889, tzinfo=utc)),
        ),
    ]
