# Generated by Django 2.2.5 on 2022-05-30 14:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activity_record', '0019_auto_20220528_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activitytype',
            field=models.CharField(choices=[('Leave', 'leave'), ('Appointment', 'appointment'), ('Break', 'break')], default='appointment', max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='addedd_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 14, 8, 44, 213724, tzinfo=utc)),
        ),
    ]
