# Generated by Django 2.2.5 on 2022-05-30 16:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activity_record', '0021_auto_20220530_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activitytype',
            field=models.CharField(choices=[('Leave', 'Leave'), ('Appointment', 'Appointment'), ('Break', 'Break')], default='Appointment', max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='addedd_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 16, 38, 20, 270252, tzinfo=utc)),
        ),
    ]
