# Generated by Django 2.2.5 on 2022-05-31 05:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activity_record', '0052_auto_20220531_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='addedd_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 5, 45, 16, 717812, tzinfo=utc)),
        ),
    ]
